### ISSUE TITLE
How to make JSON Pretty?

### ISSUE THREAD

**Issue by GuckTubeYT** [gregjesl/simpleson#10]
I want to make JSON Like this

{
    "array":[
        {
            "key":"value"
        }
    ]
}

But, why its like this = {"array":[{"key":"value"}]}

    json::jobject obj2;
    obj2["key"] = "value";
    std::vector<json::jobject> vec;
    vec.push_back(obj2);
    json::jobject example;
    example["array"] = vec;
    cout << (string) example << endl;

**Comment by gregjesl** [comment]
Hey @GuckTubeYT, right now serialization makes the string as small as possible but I'm working on a method that creates a "pretty" string.

**Comment by gregjesl** [comment]
@GuckTubeYT My latest commit adds a `.pretty()` method that will generate the type of output you're looking for:
``` cpp
json::jobject obj2;
obj2["key"] = "value";
std::vector<json::jobject> vec;
vec.push_back(obj2);
json::jobject example;
example["array"] = vec;
cout << example.pretty() << endl;
```
