### ISSUE TITLE
Tryparse returns wrong boolean

### ISSUE THREAD

**Issue by simonsc-fl** [gregjesl/simpleson#15]
Just found out that the function tryparse returns **false on success** and **true when an error is thrown**, but the documentation (and probably intuition) states otherwise.

https://github.com/gregjesl/simpleson/blob/af99256fcb6f499dc05818d582b26601f1d619e3/json.h#L312

**Comment by gregjesl** [comment]
@simonsc-fl Great catch. After thinking about it, I agree: the function should return `true` if the parse was successful.
