### ISSUE TITLE
Escape \ and " char

### ISSUE THREAD

**Issue by YoannDqr** [gregjesl/simpleson#19]
Hello ! 
Thanks for your awesome work ! :)
It seems that the strings are not sanitized before being rendered. For example, the following code:
```c
    json::jobject test;
    test["a"] = "test\\aaaa";
    std::cout << (std::string)test << "\n";
```
The expected output is :
```c
{"a" : "test\\aaaa"}
```
But the current output is :
```c
{"a": "test\aaaa"}
```
Thus, it cause trouble when the payload is sent to an external API :'(

The same problem occured during the input parsing:
```c
json::jobject test2 = json::jobject::parse("{\"a\":\"test\\\\aaaaa\"}");
    std::cout << (std::string)test2["a"] << "\n";
```

The output is :
``` 
test\\aaaaa
```

The expected output is :
``` 
test\aaaaa
```

**Comment by gregjesl** [comment]
Hey @YoannDqr thanks for opening up an issue. I'll take a look into it. 

I expect the output in your first case to be `{"a": "test\aaaa"}` because the the first `\` in `test["a"] = "test\\aaaa";` is serving as the escape character for the second `\`. 

In your second case, I would expect the output to be `test\\aaaaa` so I will take a look.

**Comment by YoannDqr** [comment]
Hi ! 
Thank you for looking into this :)

For the first case, the expected output (once printed) should be `{"a": "test\\aaaa"}` and not `{"a": "test\aaaa"}` as the `\` in the initial string should be escaped in the json string leading to a double `\` in the resulting json string.

Likewise, I found a weird behavior when the string end with a backslash.
The string `std::string a = "aaaaa\\\\";` rises a parsing error but the string `std::string b = "bbbb\\\\ ";` does not. Look like strings cannot ends with `\`. It is a problem when the json is used to send folder path for example.

Best regards,

**Comment by gregjesl** [comment]
@YoannDqr sorry for the delay. You are correct, the code does not currently comply with the following implementation: ![image](https://user-images.githubusercontent.com/14158889/180487835-60c5dc6a-6dae-4587-8294-512cf3f1935a.png)

I'll make the updates over the next week. Thank you for finding this issue!

**Comment by gregjesl** [comment]
@YoannDqr I've merged a pull request into the master branch that should address the issue. I'll generate a new release soon that includes the change.
