### ISSUE TITLE
un-escaped return string json_object in json_object

### ISSUE THREAD

**Issue by zuliz95** [gregjesl/simpleson#23]
my json file:
`{
    "0": {"key": "value\""}
}`

my main code:
`void testJsonParse() {
    std::fstream fs;
    fs.open("../test.json", std::ios::in);
    if (!fs.is_open()) {
        std::cout << "open file failed" << std::endl;
        return;
    }
    std::stringstream ss;
    ss << fs.rdbuf();
    fs.close();
    json::jobject js = json::jobject::parse(ss.str());
    std::cout << "Result: " << js.as_string() << std::endl;
    std::string str = js["0"].as_string();
    json::jobject jo = json::jobject::parse(str);
    std::cout << "key: " << jo.as_string() << std::endl;
}`

and result:
`Result: {"0":{"key":"value\\\""}}
key: {"key":"value\\\""}`

**Comment by gregjesl** [comment]
Hey @zuliz95, sorry for the delay and thank you for opening up an issue. I was able to replicate the issue, it looks like it is a problem in `parse()`. I'm investigating now.
