### ISSUE TITLE
create array of json objects within an object for output

### ISSUE THREAD

**Issue by meat-loaf** [gregjesl/simpleson#3]
I'm having trouble determining if there's a way of using the library as-designed to create an object with such a structure:
`{ "item1":1,
    "item2":2,
   "item3":[{"thing1":"thing"},
      {"thing2":"thing"}]}`

I'm trying to use this in a small embedded system so C++98 support is a huge boon; however I'm struggling to understand how to create slightly more complex JSON structures with the given interface. Is it currently possible as-written? The README.md file seems a tad out-of-date since the move to header-only.
Furthermore, if it's supported it would be nice to be able to add items to such an array while building an object to be serialized, as I can't seem to find a way to do so...
Thanks!

**Comment by gregjesl** [comment]
> I'm having trouble determining if there's a way of using the library as-designed to create an object with such a structure: `{ "item1":1, "item2":2, "item3":[{"thing1":"thing"}, {"thing2":"thing"}]}`

To create such a structure, you could write
```cpp
#include "json.h"

// Create the base object
json::jobject goal;

// Add some items to the object
goal["item1"]=1;
goal["item2"]=2;

// Create an array of JSON objects
std::vector<json::jobject> myarray;

// Add an item to the array of JSON objects
json::jobject thing1;
thing1["thing1"]="thing";
myarray.push_back(thing1);

// Add a second item to the array
json::jobject thing2;
thing2["thing2"]="thing";
myarray.push_back(thing2);

// Add the array to the object
goal["item3"]=my_array;

// Serialize the result
std::string serial = (std::string)goal;
```

> I'm trying to use this in a small embedded system so C++98 support is a huge boon

I'm glad to hear there are other people who ran into the same problem as I did:  finding a simple library for embedded systems.  I wrote this as part of a project for an ESP32.  

>I'm struggling to understand how to create slightly more complex JSON structures with the given interface. 
> The README.md file seems a tad out-of-date since the move to header-only.

I got wrapped up in another project (which implements this library); thanks for bringing this up.  I'll fix up the documentation in the next day or two. 

> Is it currently possible as-written?

Yes.  You can check out the test folder for some examples.  

> Furthermore, if it's supported it would be nice to be able to add items to such an array while building an object to be serialized, as I can't seem to find a way to do so...

I'm not quite following your suggested feature.  

> Thanks!

No problem! Please let me know if there's anything else I can address.

**Comment by meat-loaf** [comment]
Ah, I see now. I was trying something along these lines, but I just wasn't using the right type of vector or assigning it the correct way. I've got it working now. Thanks much!

>I'm not quite following your suggested feature.

Don't worry about it; that comment was poorly worded and this solution fixes what I was trying to do anyway.
Thanks a lot!

**Comment by jaysonh** [comment]
> > I'm having trouble determining if there's a way of using the library as-designed to create an object with such a structure: `{ "item1":1, "item2":2, "item3":[{"thing1":"thing"}, {"thing2":"thing"}]}`
> 
> To create such a structure, you could write
> 
> ```c++
> #include "json.h"
> 
> // Create the base object
> json::jobject goal;
> 
> // Add some items to the object
> goal["item1"]=1;
> goal["item2"]=2;
> 
> // Create an array of JSON objects
> std::vector<json::jobject> myarray;
> 
> // Add an item to the array of JSON objects
> json::jobject thing1;
> thing1["thing1"]="thing";
> myarray.push_back(thing1);
> 
> // Add a second item to the array
> json::jobject thing2;
> thing2["thing2"]="thing";
> myarray.push_back(thing2);
> 
> // Add the array to the object
> goal["item3"]=my_array;
> 
> // Serialize the result
> std::string serial = (std::string)goal;
> ```
> 
> > I'm trying to use this in a small embedded system so C++98 support is a huge boon
> 
> I'm glad to hear there are other people who ran into the same problem as I did: finding a simple library for embedded systems. I wrote this as part of a project for an ESP32.
> 
> > I'm struggling to understand how to create slightly more complex JSON structures with the given interface.
> > The README.md file seems a tad out-of-date since the move to header-only.
> 
> I got wrapped up in another project (which implements this library); thanks for bringing this up. I'll fix up the documentation in the next day or two.
> 
> > Is it currently possible as-written?
> 
> Yes. You can check out the test folder for some examples.
> 
> > Furthermore, if it's supported it would be nice to be able to add items to such an array while building an object to be serialized, as I can't seem to find a way to do so...
> 
> I'm not quite following your suggested feature.
> 
> > Thanks!
> 
> No problem! Please let me know if there's anything else I can address.

how do you read back this type of object ? I have something similar but unsure of how to get the array out of the json object

**Comment by gregjesl** [comment]
I added an [examples](https://github.com/gregjesl/simpleson/tree/master/examples) folder with an example of how to read back json objects from arrays.  The example: 
``` cpp
#include "json.h"
#include <stdio.h>
#include <assert.h>

// Create a couple objects
json::jobject obj1 = json::jobject::parse("{\"hello\":\"world\"}");
json::jobject obj2;
obj2["key"] = "value";

// Put the objects in a vector
std::vector<json::jobject> vec;
vec.push_back(obj1);
vec.push_back(obj2);

// Create an object and add the array
json::jobject example;
example["array"] = vec;

// Serialize the object
std::string serial = (std::string)example;

// Print the result
printf("%s\n", serial.c_str());
// Result: {"array":[{"hello":"world"},{"key":"value"}]}

// Read back the items
std::vector<json::jobject> readbackarray = example["array"];

// Access each item
json::jobject readback1 = readbackarray[0];
assert(readback1 == obj1);
json::jobject readback2 = readbackarray[1];
assert(readback2 == obj2);
```

**Comment by samuelvgarcia** [comment]
Hi.  This JSON parser looks pretty good.  Had a question about extracting data from arrays embedded in a json string.
Let's say I have a json string like so:

[
  {
    "firstName": "Jimmy",
    "lastName": "D",
    "hobbies": [
      {
        "sport": "tennis"
      },
      {
        "music": "rock"
      }
    ]
  },
  {
    "firstName": "Sussi",
    "lastName": "Q",
    "hobbies": [
      {
        "sport": "volleyball"
      },
      {
        "music": "classical"
      }
    ]
  },
]

which is stored in a std::string s
How do I parse it since the outer level is an array?  The json::jobject::parse only works if string begins with a curly bracket "{"

Let's say there is a parsing function in the library that will create the json object as so:
json_obj = parse(s.c_str());

Is there a way to navigate the hierarchy similar to this: 
std::string music_desired = json_obj[1]["hobbies"][1]["music"];

Or do I need to keep on recursively create std::vector<json::jobject>, extract a json record, and then create another std::vector<json::jobject> ?

**Comment by gregjesl** [comment]
> How do I parse it since the outer level is an array? The json::jobject::parse only works if string begins with a curly bracket "{"

I'll need to close Issue #4 to be able to parse a JSON array as the root element; I'll give that a shot this week. 

> Is there a way to navigate the hierarchy similar to this:
std::string music_desired = json_obj[1]["hobbies"][1]["music"];
> 
> Or do I need to keep on recursively create std::vectorjson::jobject, extract a json record, and then create another std::vectorjson::jobject,and so on ?

The ability to reference a JSON object in an array without casting it to a vector of JSON objects first is a feature I hadn't thought of, I'll keep this issue open until I implement it.

**Comment by samuelvgarcia** [comment]
Thanks for the excellent project.  I needed something that could run on an embedded system and this fit the bill.

**Comment by gregjesl** [comment]
@samuelvgarcia The latest commit supports root arrays and the ability to reference elements nested deep in the object. 
> Is there a way to navigate the hierarchy similar to this:
> std::string music_desired = json_obj[1]["hobbies"][1]["music"];

This should now compile and return "classical"

**Comment by samuelvgarcia** [comment]
When I try running the code:
std::string music_desired = json_obj[1]["hobbies"][1]["music"];

I get two compiler errors:
'json::jobject::operator []': 3 overloads have similar conversions	

more than one operator "[]" matches these operands

**Comment by gregjesl** [comment]
@samuelvgarcia That's what I get for not testing my suggestion 😬 . The latest commit includes [your specific example](https://github.com/gregjesl/simpleson/blob/2c06e35c48473dc4178b39ad88f0e0f66c3aaa0a/examples/rootarray.cpp#L5-L40) in the examples folder.

**Comment by samuelvgarcia** [comment]
@gregjesl.  There might still be a bug.  If instead of using the index 1 of the array, I try index 0, it didn't compile for me.

Error	C2666	'json::jobject::operator []': 3 overloads have similar conversions	

Error (active)	E0350	more than one operator "[]" matches these operands:	
            function "json::jobject::operator[](std::string key)"
            function "json::jobject::operator[](size_t index) const"
            operand types are: json::jobject [ int ]

**Comment by gregjesl** [comment]
@samuelvgarcia Good catch, I didn't remove the `[]` operator for arrays when the array is the base object. The latest commit now includes an example with an index access of 0.

**Comment by samuelvgarcia** [comment]
@gregjesl Looks good.  

For anyone in the future coming across this ticket, this is the way to access embedded fields:
 json_obj.array(0).get("hobbies").array(1).get("music")
