### ISSUE TITLE
Compile warnings with clang

### ISSUE THREAD

**Issue by sampscl** [gregjesl/simpleson#5]
On MacOS, clang reports the following warning:

> In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:275:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__bit_reference:16:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:644:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1881:58: warning: destructor called on
      non-final 'json::jobject' that has virtual functions but non-virtual destructor [-Wdelete-non-abstract-non-virtual-dtor]
    _LIBCPP_INLINE_VISIBILITY void destroy(pointer __p) {__p->~_Tp();}

This warning is generated because there are virtual functions in `json::jobject` but no virtual destructor. There should be a virtual destructor, but `json::jobject` also inherits from `std::vector`, which it also should not do.

**Comment by gregjesl** [comment]
@sampscl Good catch.  I wrote the original code a while ago when I was still pretty new to C++.  I've got an update that fixes it.  Thanks for pointing this out!
